ACTION_SPACE = {
    0: "ANALYZE_TASK",
    1: "REQUEST_CLARIFICATION",
    2: "ACCEPT_SIMPLE_TASK",
    3: "DECOMPOSE_TASK",
    4: "EXECUTE_PARALLEL",
    5: "EXECUTE_NEXT_TASK",
    6: "SKIP_TASK",
    7: "REFINE_PLAN",
    8: "ABORT_REFINEMENT",
    9: "SEND_FEEDBACK",
    10: "CANCEL_EXECUTION"
}

NUM_ACTIONS = len(ACTION_SPACE)

